import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCustomerTables1742225839841 implements MigrationInterface {
    name = 'CreateCustomerTables1742225839841'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "organizations_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_organization_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "permissions_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_product_categories_parent"`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP CONSTRAINT "product_items_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "product_quotations" DROP CONSTRAINT "FK_7c843dd2709193981b0bce772e6"`);
        await queryRunner.query(`ALTER TABLE "product_quotations" DROP CONSTRAINT "FK_a62de57278a2bb74d8f0ab47399"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_organizations" DROP CONSTRAINT "role_organizations_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_organizations" DROP CONSTRAINT "role_organizations_organization_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."product_items_category_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."product_items_created_by_idx"`);
        await queryRunner.query(`DROP INDEX "public"."product_items_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_quotations_product_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_quotations_supplier_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_quotations_is_latest"`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "passportNo" character varying(50) NOT NULL, "gender" character varying(10) NOT NULL, "country" character varying(50) NOT NULL, "birthDate" bigint, "issueDate" bigint, "expiryDate" bigint, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e6c15fb94823d2cc81e520d7b71" UNIQUE ("passportNo"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "visas" ("id" SERIAL NOT NULL, "customerId" integer NOT NULL, "country" character varying(50) NOT NULL, "visaType" character varying(50) NOT NULL, "visaName" character varying(100) NOT NULL, "issueDate" bigint, "expiryDate" bigint, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef97e93b657ad9da6434135df38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "role_organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "organizations_code_key"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "code" character varying`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "UQ_7e27c3b62c681fbe3e2322535f2" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "sort" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "sort" SET DEFAULT '100'`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "status" character varying NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_username_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "data_scope"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "data_scope" character varying NOT NULL DEFAULT 'self'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "permissions_code_key"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "path" character varying`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "component"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "component" character varying`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "icon" character varying`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "sort" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "status" character varying NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "roles_code_key"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "sort" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "status" character varying NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "data_scope"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "data_scope" character varying NOT NULL DEFAULT 'self'`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "UQ_product_categories_code"`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "status" character varying NOT NULL DEFAULT 'offline'`);
        await queryRunner.query(`ALTER TABLE "product_items" ALTER COLUMN "sort" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_countries" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_countries" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7c9743b25ebdc9eb7a037a274" ON "role_organizations" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d10be879e8a53ad12e83a6f1e" ON "role_organizations" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "FK_f3a7c9411eaa5f9cbc5363de331" FOREIGN KEY ("parent_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_21a659804ed7bf61eb91688dea7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_e152e0aa9e0df7ed44539db894c" FOREIGN KEY ("parent_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_cbf04073e03d8873ae0662053a3" FOREIGN KEY ("parentId") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD CONSTRAINT "FK_ec4f909a8caa5c340e627a89d42" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD CONSTRAINT "FK_71e899b5e1aecb8ad1480a57c78" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visas" ADD CONSTRAINT "FK_c77a4135320293a7e557f4afc8c" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ADD CONSTRAINT "FK_7c843dd2709193981b0bce772e6" FOREIGN KEY ("product_id") REFERENCES "product_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ADD CONSTRAINT "FK_a62de57278a2bb74d8f0ab47399" FOREIGN KEY ("supplier_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ADD CONSTRAINT "FK_46bf42c3d919d251df8d3e073c2" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_organizations" ADD CONSTRAINT "FK_d7c9743b25ebdc9eb7a037a2745" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_organizations" ADD CONSTRAINT "FK_6d10be879e8a53ad12e83a6f1e5" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_organizations" DROP CONSTRAINT "FK_6d10be879e8a53ad12e83a6f1e5"`);
        await queryRunner.query(`ALTER TABLE "role_organizations" DROP CONSTRAINT "FK_d7c9743b25ebdc9eb7a037a2745"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "product_quotations" DROP CONSTRAINT "FK_46bf42c3d919d251df8d3e073c2"`);
        await queryRunner.query(`ALTER TABLE "product_quotations" DROP CONSTRAINT "FK_a62de57278a2bb74d8f0ab47399"`);
        await queryRunner.query(`ALTER TABLE "product_quotations" DROP CONSTRAINT "FK_7c843dd2709193981b0bce772e6"`);
        await queryRunner.query(`ALTER TABLE "visas" DROP CONSTRAINT "FK_c77a4135320293a7e557f4afc8c"`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP CONSTRAINT "FK_71e899b5e1aecb8ad1480a57c78"`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP CONSTRAINT "FK_ec4f909a8caa5c340e627a89d42"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_cbf04073e03d8873ae0662053a3"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_e152e0aa9e0df7ed44539db894c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_21a659804ed7bf61eb91688dea7"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "FK_f3a7c9411eaa5f9cbc5363de331"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d10be879e8a53ad12e83a6f1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7c9743b25ebdc9eb7a037a274"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_countries" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_countries" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_items" ALTER COLUMN "sort" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "status" character varying(50) NOT NULL DEFAULT 'offline'`);
        await queryRunner.query(`ALTER TABLE "product_items" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "UQ_product_categories_code" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "data_scope"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "data_scope" character varying(20) DEFAULT 'self'`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "status" character DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "sort" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "roles_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "status" character DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "sort" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "icon" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "component"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "component" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "path" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "UQ_8dad765629e83229da6feda1c1d"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "code" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "permissions_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "data_scope"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "data_scope" character varying(20) DEFAULT 'self'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_username_key" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "status" character DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "sort" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "sort" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "UQ_7e27c3b62c681fbe3e2322535f2"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "code" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "organizations_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "role_organizations" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP TABLE "visas"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`CREATE INDEX "idx_product_quotations_is_latest" ON "product_quotations" ("is_latest") `);
        await queryRunner.query(`CREATE INDEX "idx_product_quotations_supplier_id" ON "product_quotations" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_quotations_product_id" ON "product_quotations" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "product_items_status_idx" ON "product_items" ("status") `);
        await queryRunner.query(`CREATE INDEX "product_items_created_by_idx" ON "product_items" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "product_items_category_id_idx" ON "product_items" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "role_organizations" ADD CONSTRAINT "role_organizations_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_organizations" ADD CONSTRAINT "role_organizations_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ADD CONSTRAINT "FK_a62de57278a2bb74d8f0ab47399" FOREIGN KEY ("supplier_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_quotations" ADD CONSTRAINT "FK_7c843dd2709193981b0bce772e6" FOREIGN KEY ("product_id") REFERENCES "product_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_items" ADD CONSTRAINT "product_items_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_product_categories_parent" FOREIGN KEY ("parentId") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "permissions_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "organizations_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
